{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.rusthero",
    "module": "version-checker",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "version-checker-1.0.0.jar",
          "url": "version-checker-1.0.0.jar",
          "size": 3217,
          "sha512": "e1a41f9cf04a8b1d837aff9ecc7314db9cd402a3022398b68c0ab575d3a41ce533f181981d336b3cbb58a2007ebfe27ab2a43f01f46b4621e819dcc592544f97",
          "sha256": "14f55b0316867aee1197bd9559123d5bd330fbc03d6260b872907b8eea9d6101",
          "sha1": "a3c57a22d31b02727e72fdd4caa4c661a68755b2",
          "md5": "39ece3b5424b25ce0dba28cf959c5c6c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "version-checker-1.0.0.jar",
          "url": "version-checker-1.0.0.jar",
          "size": 3217,
          "sha512": "e1a41f9cf04a8b1d837aff9ecc7314db9cd402a3022398b68c0ab575d3a41ce533f181981d336b3cbb58a2007ebfe27ab2a43f01f46b4621e819dcc592544f97",
          "sha256": "14f55b0316867aee1197bd9559123d5bd330fbc03d6260b872907b8eea9d6101",
          "sha1": "a3c57a22d31b02727e72fdd4caa4c661a68755b2",
          "md5": "39ece3b5424b25ce0dba28cf959c5c6c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "version-checker-1.0.0-javadoc.jar",
          "url": "version-checker-1.0.0-javadoc.jar",
          "size": 81616,
          "sha512": "2fbad57c6b2f5692e964e9ed27746e76b11af871971b29062b871283a5e4389a25dce15bc974b5486c04572618da48f9c001d266d916c3a7c5b1fd93dc25d676",
          "sha256": "d72d18cfd11fda9e72e9505a81daab8ca617cbc76f37f5ad6e63d9f95031efcd",
          "sha1": "10dc5fa5bab918c3771ad5d4d142531ffa778108",
          "md5": "ed2c30441eda1e8f1e45b12b932aada1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "version-checker-1.0.0-sources.jar",
          "url": "version-checker-1.0.0-sources.jar",
          "size": 3293,
          "sha512": "fefc2b5bf3b6b2b4af6481378f4253496470696711c95c8da2ce916f596b89ff4eff6b59fb159f82bb347c7054eb535353d8b676e8d3897f1f396be9d7e2e596",
          "sha256": "3b71a5ddf1efaf7464beb1b7d2c7d7552f74bb9fa1cf5a6c455a060007e267f1",
          "sha1": "05e62485d22452af4a7e5944b034cc2055df3c2b",
          "md5": "e6a8b531a5682868c4a27bc9a7793d7b"
        }
      ]
    }
  ]
}
